spring:
  datasource:
    drive-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

logging:
  level:
    org.jetbrains.exposed.sql.transactions: DEBUG
    org.springframework.jdbc.core: DEBUG